# Variables

# default versions
GRAFANA_VERSION="${GRAFANA_VERSION:-6.1.4}"
CLOUDSQL_PROXY_VERSION="${CLOUDSQL_PROXY_VERSION:-1.13}"

# dependencies paths
GRAFANA_DIR="${DEPS_DIR}/${DEPS_IDX}/grafana"
SQLPROXY_DIR="${DEPS_DIR}/${DEPS_IDX}/cloud_sql_proxy"


GRAFANA_MIN_VERSION="6.0.0"
