{
 "title": "CF Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average assigned memory utilization across whole CF",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg((sum(min(firehose_container_metric_memory_bytes/1024/1024) by (instance_index, application_id)) by (application_id) / on(application_id) group_left(space_name) (cf_application_memory_mb * on (application_id) group_left(space_name) sum(cf_application_instances) by (application_id)))*100) by (organization_name)"
    }
   ]
  },
  {
   "title": "Total Number of active applications",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(cf_application_info{state=\"STARTED\"}) by (application_name))"
    }
   ]
  },
  {
   "title": "Total number of active instances",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(sum(cf_application_instances{state=\"STARTED\"}) by (organization_name))"
    }
   ]
  },
  {
   "title": "Total memory assigned by apps",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 4 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cf_application_memory_mb * on (application_id) group_right(space_name) sum(cf_application_instances{state=\"STARTED\"}) by (application_id)) "
    }
   ]
  },
  {
   "title": "Memory assigned per org",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 6 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(cf_application_memory_mb * on (application_id) group_right(organization_name) sum(cf_application_instances{state=\"STARTED\"}) by (application_id)) by (organization_name))",
     "legendFormat": "{{organization_name}}"
    },
    {}
   ]
  },
  {
   "title": "Predicted Cost per Org for next month",
   "type": "grafana-piechart-panel",
   "description": "This cost is derived 7.5$ * memory usage. This  number has come from our past mem/cost ratio. It is a rough approximation of the cost. ",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 6 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(cf_application_memory_mb * on (application_id) group_right(organization_name) sum(cf_application_instances{state=\"STARTED\"}) by (application_id)) by (organization_name)) /1024 * 7.5",
     "legendFormat": "{{organization_name}}"
    },
    {}
   ]
  },
  {
   "title": "Number of applications per org",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(cf_application_info{state=\"STARTED\"}) by (organization_name))",
     "legendFormat": "{{organization_name}}"
    }
   ]
  },
  {
   "title": "Average Assigned Memory Utilization per Org",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(avg((sum(min(firehose_container_metric_memory_bytes/1024/1024) by (instance_index, application_id)) by (application_id) / on(application_id) group_right(space_name) (cf_application_memory_mb * on (application_id) group_left(space_name) sum(cf_application_instances) by (application_id)))*100) by (organization_name))",
     "legendFormat": "{{organization_name}}"
    }
   ]
  },
  {
   "title": "Services Offered",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 32 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "cf_service_info",
     "legendFormat": "{{service_label}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Org Quota",
   "type": "table",
   "gridPos": { "h": 13, "w": 18, "x": 6, "y": 32 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "cf_organization_info",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "expr": "min(cf_organization_instance_memory_mb_limit) by (organization_name)"
    },
    {
     "expr": "min(cf_organization_total_routes_quota) by (organization_name)"
    },
    {
     "expr": "min(cf_organization_total_memory_mb_quota) by (organization_name) *(1000/1024)"
    }
   ]
  }
 ]
}